// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQAbjMFDORJKX_cfmHLx6rnJzj02g76zA',
    appId: '1:520496778717:web:6381e129255bd1634b7a34',
    messagingSenderId: '520496778717',
    projectId: 'crud-9d682',
    authDomain: 'crud-9d682.firebaseapp.com',
    storageBucket: 'crud-9d682.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU5FL12-NlfKhO0gO9LedpqTBmyRwZaC0',
    appId: '1:520496778717:android:8b41f7397c7e21414b7a34',
    messagingSenderId: '520496778717',
    projectId: 'crud-9d682',
    storageBucket: 'crud-9d682.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfMmbiJV_sTiZhorEGUJHzqYHH82of1do',
    appId: '1:520496778717:ios:31f566ce0358064c4b7a34',
    messagingSenderId: '520496778717',
    projectId: 'crud-9d682',
    storageBucket: 'crud-9d682.appspot.com',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfMmbiJV_sTiZhorEGUJHzqYHH82of1do',
    appId: '1:520496778717:ios:31f566ce0358064c4b7a34',
    messagingSenderId: '520496778717',
    projectId: 'crud-9d682',
    storageBucket: 'crud-9d682.appspot.com',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQAbjMFDORJKX_cfmHLx6rnJzj02g76zA',
    appId: '1:520496778717:web:f0b373496fb924724b7a34',
    messagingSenderId: '520496778717',
    projectId: 'crud-9d682',
    authDomain: 'crud-9d682.firebaseapp.com',
    storageBucket: 'crud-9d682.appspot.com',
  );
}
